server:
  port: 6868

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    register-with-eureka: false  #是否将自己注册到eureka
    fetch-registry: false  #是否从eureka获取信息