#server:
#  port:

#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ceshi?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver

    #redis配置
  redis:
    database: 5
    host: locahost
    port: 6379
    password: 123456  #默认为空


#日志默认级别debug方式
logging:
  level: debug
  file: logs/common-db-log.log

